### ISSUE TITLE
Spring echo sample not working when deployed on Azure

### ISSUE THREAD

**Issue by diskdan** [microsoft/botbuilder-java#123]
## Version
Build from latest master branch.

## Describe the bug
I have cloned, built and run the spring echo sample locally and confirmed that I can communicate with the Microsoft Bot Emulator locally.

I have successfully deployed to Azure as per the instructions.

When I test the bot with the "Test in WebChat" functionality on Azure I get the following error. I have confirmed that the message is received and it seems to be an error when sending a message back to the bot:

java.util.concurrent.CompletionException: com.microsoft.bot.connector.rest.ErrorResponseException: Status code 400, {"error": {"code": "BadSyntax","message": "Invalid or missing Activity in request"}}at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_212]at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_212]at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[na:1.8.0_212]at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[na:1.8.0_212]at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_212]at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_212]at retrofit2.CompletableFutureCallAdapterFactory$ResponseCallAdapter$2.onResponse(CompletableFutureCallAdapterFactory.java:119) ~[retrofit-2.5.0.jar!/:na]at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129) ~[retrofit-2.5.0.jar!/:na]at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[okhttp-3.12.2.jar!/:na]at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.12.2.jar!/:na]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]Caused by: com.microsoft.bot.connector.rest.ErrorResponseException: Status code 400, {"error": {"code": "BadSyntax","message": "Invalid or missing Activity in request"}}at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122) ~[client-runtime-1.6.12.jar!/:na]at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56) ~[azure-client-runtime-1.6.12.jar!/:na]at com.microsoft.bot.connector.rest.RestConversations.replyToActivityDelegate(RestConversations.java:341) ~[bot-connector-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT]at com.microsoft.bot.connector.rest.RestConversations.lambda$replyToActivity$4(RestConversations.java:324) ~[bot-connector-4.0.0-SNAPSHOT.jar!/:4.0.0-SNAPSHOT]at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_212]... 10 common frames omitted

## To Reproduce
Follow steps as described above.

## Expected behavior
The bot should work.

## Additional context
I suspect this is due to a versioning issue, i.e. that the Azure protocol has changed and the corresponding java library is not up to date. I tried updating to the latest version but to no avail.

Furthermore I have tried deploying a bot remotely and registering it with Azure. This gives the same error from "Test in WebChat". Interestingly, I am able to add this bot to Skype and send messages. However the error message is slightly different:

java.util.concurrent.CompletionException: com.microsoft.bot.connector.rest.ErrorResponseException: Status code 400, {"error":{"code":"BadSyntax","message":"Payload is incorrect, field is in the wrong format: timestamp"}}
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_222]
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_222]
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[na:1.8.0_222]
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[na:1.8.0_222]
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_222]
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_222]
    at retrofit2.CompletableFutureCallAdapterFactory$ResponseCallAdapter$2.onResponse(CompletableFutureCallAdapterFactory.java:119) ~[retrofit-2.5.0.jar:na]
    at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129) ~[retrofit-2.5.0.jar:na]
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[okhttp-3.12.2.jar:na]
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.12.2.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]

[bug]

**Comment by v-kydela** [comment]
Hello @diskdan - Are you saying you followed the instructions [here](https://github.com/microsoft/botbuilder-java/blob/master/samples/spring-echo/README.md)?

There are multiple possibilities for which set of instructions you followed. Did you deploy to a new resource group or an existing resource group?

**Comment by tracyboehrer** [comment]
Have you tried cloning from the 4.6 preview 2 branch? Master is changing quickly as Bot-builder is added. I suspect there are some issues with the change from joda-time to Java 8 Date & Time.

________________________________

**Comment by diskdan** [comment]
Hi, many thanks for getting back to me on this and apologies for lack of clarity.

I deployed to an existing resource group following the instructions in the readme.md file in the spring-echo sample project.

I will try the recommended branch - hopefully this will resolve the issues (I am keeping my fingers crossed).

**Comment by diskdan** [comment]
Great news, switching to the branch solved my issues. I guess I should have thought of trying this myself... Many, many thanks for your help on this !

**Comment by tracyboehrer** [comment]
Glad to here that.  I merged some fixes for master.  However, I would recommend sticking with the 4.6-preview2 branch for now.  At the end of October, there will be a Preview 3 that includes the bot-builder module with almost all of the functionality from dotnet's bot-builder.
