### ISSUE TITLE
IllegalAccessError on some Java versions

### ISSUE THREAD

**Issue by dmoidl** [microsoft/botbuilder-java#1307]
## Version
bot-integration-spring:4.14.0

## Describe the bug
`TeamsActivityHandler.onInvokeActivity` fails with `java.lang.IllegalAccessError` on Java 16

## To Reproduce
1. Run any sample that includes MS Teams, eg. [this one](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/50.teams-messaging-extensions-search) __using JRE 16__.
2. Try to invoke the bot via Teams
3. Observe the following error:
```
java.util.concurrent.CompletionException: java.lang.IllegalAccessError: class com.microsoft.bot.builder.teams.TeamsActivityHandler$$Lambda$718/0x000000080105ade8 tried to access protected method 'com.microsoft.bot.builder.InvokeResponse com.microsoft.bot.builder.ActivityHandler.createInvokeResponse(java.lang.Object)' (com.microsoft.bot.builder.teams.TeamsActivityHandler$$Lambda$718/0x000000080105ade8 and com.microsoft.bot.builder.ActivityHandler are in unnamed module of loader 'app')
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1769)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalAccessError: class com.microsoft.bot.builder.teams.TeamsActivityHandler$$Lambda$718/0x000000080105ade8 tried to access protected method 'com.microsoft.bot.builder.InvokeResponse com.microsoft.bot.builder.ActivityHandler.createInvokeResponse(java.lang.Object)' (com.microsoft.bot.builder.teams.TeamsActivityHandler$$Lambda$718/0x000000080105ade8 and com.microsoft.bot.builder.ActivityHandler are in unnamed module of loader 'app')
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 10 more
```

## Expected behavior
The code would not fail with the error.

## Additional context
I believe the problem is related to a possible bug in the Java compiler discussed [here](https://coderanch.com/t/664583/java/Static-methods-inheritance-java-lang). Apparently, the call to `ActivityHandler.createInvokeResponse` should not be allowed, but the compiler cannot detect it in compile time. 
This is rather problematic. All the more so as some JREs do not mind this (eg. version 11) and the code works fine while others (such as 16) do and it breaks in runtime.
I think (but haven't tested) that referencing `TeamsActivityHandler::createInvokeResponse` rather than `ActivityHandler::createInvokeResponse` may solve the issue. I would, however, recommend to inspect the code for other possible instances of the same issue.

**Comment by tracyboehrer** [comment]
@dmoidl Thanks!  We'll take a look.  It does seem like the link you included is related.  Not even sure why that method is static.

**Comment by tracyboehrer** [comment]
@dmoidl I was able to reproduce by running unit tests using Java 16.  I submitted a PR with the correction.  TBD when a patch release will be done.
