### ISSUE TITLE
InaccessibleObjectException - Unable to make field private static final long java.util.ArrayList.serialVersionUID accessible

### ISSUE THREAD

**Issue by esfomeado** [microsoft/botbuilder-java#1474]
## Version
bot-integration-spring:4.14.2

## Describe the bug
When continuing a conversation I get an InaccessibleObjectException on `openjdk17`

## To Reproduce
```
private final BotFrameworkHttpAdapter adapter;

adapter.continueConversation(...)
```

```
java.util.concurrent.CompletionException: java.lang.reflect.InaccessibleObjectException: Unable to make field private static final long java.util.ArrayList.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @7c30a502
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static final long java.util.ArrayList.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @7c30a502
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
at com.microsoft.bot.restclient.Validator.validateClass(Validator.java:73)
at com.microsoft.bot.restclient.Validator.validate(Validator.java:60)
at com.microsoft.bot.restclient.Validator.validateClass(Validator.java:107)
at com.microsoft.bot.restclient.Validator.validate(Validator.java:60)
at com.microsoft.bot.restclient.Validator.validateClass(Validator.java:100)
at com.microsoft.bot.restclient.Validator.validate(Validator.java:60)
at com.microsoft.bot.connector.rest.RestConversations.replyToActivity(RestConversations.java:458)
at com.microsoft.bot.connector.Conversations.replyToActivity(Conversations.java:202)
at com.microsoft.bot.builder.BotFrameworkAdapter.lambda$sendActivities$5(BotFrameworkAdapter.java:618)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
```

## Expected behavior
It should just work

## Additional context
Running on openjdk-17 on docker with alpine image

https://openjdk.org/jeps/403

**Comment by esfomeado** [comment]
If you add a property to the Activity you can trigger this issue as well when you try to send it.

**Comment by dmvtech** [comment]
Investigating

**Comment by dmvtech** [comment]
Hi @esfomeado 

I don't know that we have done any thorough testing past JDK 8. Possibly some quick tests with JDK 11.

- Do you have a simple sample that could be used to reproduce the problem?
- Have you tested with JDK 8 or 11?

**Comment by johnmiroki** [comment]
I forgot how but I ran into the same problem, a quick fix is to add this VM option:
--add-opens java.base/java.util=ALL-UNNAMED

**Comment by esfomeado** [comment]
@johnmiroki Thanks, that's what I'm using as well as workaround.

**Comment by rbuibas** [comment]
I have recently run into this issue (with Java 17) while trying to implement a Bot <> Skill communication and calling the _handleReplyToActivity_ of the [ChannelServiceHandler](https://github.com/microsoft/botbuilder-java/blob/main/libraries/bot-builder/src/main/java/com/microsoft/bot/builder/ChannelServiceHandler.java).
(tracked the problem into the [Validator class](https://github.com/microsoft/botbuilder-java/blob/main/libraries/bot-connector/src/main/java/com/microsoft/bot/restclient/Validator.java)).

I am just wondering if there is an intention to fix this or if there is a way to disable the validation?

Thanks!
