### ISSUE TITLE
Error in Sending Adaptive Card with People Picker to Message

### ISSUE THREAD

**Issue by johnmiroki** [microsoft/botbuilder-java#1476]
## Version
What package version of the SDK are you using.
4.14.2

## Describe the bug
Give a clear and concise description of what the bug is.
When sending message using adaptive card that contains a People Picker with dataset, Activity can't be serialized (FlatterningSerializer throws error):

Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.ArrayNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')
	at com.microsoft.bot.restclient.serializer.FlatteningSerializer.serialize(FlatteningSerializer.java:187) ~[bot-connector-4.14.2.jar:4.14.2]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.13.3.jar:2.13.3]
	... 27 common frames omitted

## To Reproduce
1 Prepare an adaptive card containing People Picker:
```json
    {
      "type": "Input.ChoiceSet",
      "choices": [],
      "choices.data": {
        "type": "Data.Query",
        "dataset": "graph.microsoft.com/users?scope=currentContext"
      },
      "isMultiSelect": true,
      "placeholder": "Choose at least one person for this feedback",
      "label": "Request to",
      "style": "filtered",
      "id": "userId"
    },
```
2. Send card as message
3. See error in log

## Expected behavior
Give a clear and concise description of what you expected to happen.
Expect adaptive card to be sent to chat

## Additional context
The same adaptive card works for Task Module.
The problem is in FlatterningSerializer, where it tries to flat "choices.data", how ever, this can't be done, for the expected flatterned data is:
```js
choices: {
  data: {..}
}
```
but there's already a `choices: []` existing. These two can't match.

**Comment by tdurnford** [comment]
@johnmiroki What channel are you using?

**Comment by ramfattah** [comment]
Thanks, @johnmiroki, I'm investigating this.

**Comment by ramfattah** [comment]
Hi @johnmiroki, 

Thanks for raising this issue, I was able to repro.

Looks like when sending [People Picker](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/people-picker?tabs=desktop) in Adaptive Cards, the following error message is thrown:
``` 
Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.ArrayNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')
	at com.microsoft.bot.restclient.serializer.FlatteningSerializer.serialize(FlatteningSerializer.java:187) ~[bot-connector-4.14.1.jar:4.14.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.11.3.jar:2.11.3]
	... 25 common frames omitted
```

Error source code: 
/bot-connector/src/main/java/com/microsoft/bot/restclient/serializer/[FlatteningSerializer.java](https://github.com/microsoft/botbuilder-java/blob/4029851c81b6c5ee70248402683f43c3f35fd162/libraries/bot-connector/src/main/java/com/microsoft/bot/restclient/serializer/FlatteningSerializer.java)

**Comment by johnmiroki** [comment]
@ramfattah Thank you for the confirmation!

**Comment by ramfattah** [comment]
Thank you @johnmiroki, we are working on this fix for the next patch release.

**Comment by ramfattah** [comment]
#### Call stack to FlatterningSerializer:

> serialize:155, FlatteningSerializer (com.microsoft.bot.restclient.serializer)
_serialize:480, DefaultSerializerProvider (com.fasterxml.jackson.databind.ser)
serializeValue:319, DefaultSerializerProvider (com.fasterxml.jackson.databind.ser)
serialize:1516, ObjectWriter$Prefetch (com.fasterxml.jackson.databind)
_writeValueAndClose:1217, ObjectWriter (com.fasterxml.jackson.databind)
writeValueAsBytes:1110, ObjectWriter (com.fasterxml.jackson.databind)
convert:75, JacksonConverterFactory$JacksonRequestBodyConverter (com.microsoft.bot.restclient.serializer)
convert:66, JacksonConverterFactory$JacksonRequestBodyConverter (com.microsoft.bot.restclient.serializer)
apply:355, ParameterHandler$Body (retrofit2)
create:108, RequestFactory (retrofit2)
createRawCall:190, OkHttpCall (retrofit2)
enqueue:100, OkHttpCall (retrofit2)
adapt:117, CompletableFutureCallAdapterFactory$ResponseCallAdapter (retrofit2)
adapt:94, CompletableFutureCallAdapterFactory$ResponseCallAdapter (retrofit2)
invoke:89, HttpServiceMethod (retrofit2)
invoke:147, Retrofit$1 (retrofit2)
replyToActivity:-1, $Proxy85 (com.microsoft.bot.connector.rest)
replyToActivity:460, RestConversations (com.microsoft.bot.connector.rest)
replyToActivity:202, Conversations (com.microsoft.bot.connector)
lambda$sendActivities$5:618, BotFrameworkAdapter (com.microsoft.bot.builder)
get:-1, 1272797835 (com.microsoft.bot.builder.BotFrameworkAdapter$$Lambda$723)
run$$$capture:1700, CompletableFuture$AsyncSupply (java.util.concurrent)
run:-1, CompletableFuture$AsyncSupply (java.util.concurrent)
> - Async stack trace
<init>:1686, CompletableFuture$AsyncSupply (java.util.concurrent)
asyncSupplyStage:1714, CompletableFuture (java.util.concurrent)
supplyAsync:1931, CompletableFuture (java.util.concurrent)
sendActivities:579, BotFrameworkAdapter (com.microsoft.bot.builder)
sendActivitiesThroughAdapter:418, TurnContextImpl (com.microsoft.bot.builder)
sendActivities:385, TurnContextImpl (com.microsoft.bot.builder)
sendActivity:346, TurnContextImpl (com.microsoft.bot.builder)
lambda$onMembersAdded$1:51, TeamsBot (com.microsoft.bot.sample.teamsauth)
accept:195, ReferencePipeline$3$1 (java.util.stream)
accept:177, ReferencePipeline$2$1 (java.util.stream)
forEachRemaining:1655, ArrayList$ArrayListSpliterator (java.util)
copyInto:484, AbstractPipeline (java.util.stream)
wrapAndCopyInto:474, AbstractPipeline (java.util.stream)
evaluateSequential:913, ReduceOps$ReduceOp (java.util.stream)
evaluate:234, AbstractPipeline (java.util.stream)
collect:578, ReferencePipeline (java.util.stream)
onMembersAdded:53, TeamsBot (com.microsoft.bot.sample.teamsauth)
onConversationUpdateActivity:168, ActivityHandler (com.microsoft.bot.builder)
onConversationUpdateActivity:624, TeamsActivityHandler (com.microsoft.bot.builder.teams)
onTurn:81, ActivityHandler (com.microsoft.bot.builder)
onTurn:44, DialogBot (com.microsoft.bot.sample.teamsauth)
receiveActivityInternal:99, MiddlewareSet (com.microsoft.bot.builder)
lambda$receiveActivityInternal$1:110, MiddlewareSet (com.microsoft.bot.builder)
onTurn:1430, BotFrameworkAdapter$TenantIdWorkaroundForTeamsMiddleware (com.microsoft.bot.builder)
receiveActivityInternal:109, MiddlewareSet (com.microsoft.bot.builder)
receiveActivityInternal:74, MiddlewareSet (com.microsoft.bot.builder)
receiveActivityWithStatus:67, MiddlewareSet (com.microsoft.bot.builder)
runPipeline:206, BotAdapter (com.microsoft.bot.builder)
lambda$processActivity$2:478, BotFrameworkAdapter (com.microsoft.bot.builder)
uniComposeStage:1106, CompletableFuture (java.util.concurrent)
thenCompose:2235, CompletableFuture (java.util.concurrent)
processActivity:476, BotFrameworkAdapter (com.microsoft.bot.builder)
lambda$processActivity$1:433, BotFrameworkAdapter (com.microsoft.bot.builder)
tryFire:1072, CompletableFuture$UniCompose (java.util.concurrent)
postComplete:506, CompletableFuture (java.util.concurrent)
run$$$capture:1705, CompletableFuture$AsyncSupply (java.util.concurrent)
run:-1, CompletableFuture$AsyncSupply (java.util.concurrent)
> - Async stack trace
<init>:1686, CompletableFuture$AsyncSupply (java.util.concurrent)
asyncSupplyStage:1714, CompletableFuture (java.util.concurrent)
supplyAsync:1931, CompletableFuture (java.util.concurrent)
validateToken:142, JwtTokenExtractor (com.microsoft.bot.connector.authentication)
getIdentity:127, JwtTokenExtractor (com.microsoft.bot.connector.authentication)
getIdentity:96, JwtTokenExtractor (com.microsoft.bot.connector.authentication)
getIdentity:74, JwtTokenExtractor (com.microsoft.bot.connector.authentication)
authenticateToken:112, ChannelValidation (com.microsoft.bot.connector.authentication)
authenticateToken:206, ChannelValidation (com.microsoft.bot.connector.authentication)
authenticateToken:201, JwtTokenValidation (com.microsoft.bot.connector.authentication)
validateAuthHeader:159, JwtTokenValidation (com.microsoft.bot.connector.authentication)
authenticateRequest:98, JwtTokenValidation (com.microsoft.bot.connector.authentication)
processActivity:432, BotFrameworkAdapter (com.microsoft.bot.builder)
processIncomingActivity:102, BotFrameworkHttpAdapter (com.microsoft.bot.integration)
incoming:84, BotController (com.microsoft.bot.integration.spring)
invoke0:-2, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:62, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:566, Method (java.lang.reflect)
doInvoke:197, InvocableHandlerMethod (org.springframework.web.method.support)
invokeForRequest:141, InvocableHandlerMethod (org.springframework.web.method.support)
invokeAndHandle:106, ServletInvocableHandlerMethod (org.springframework.web.servlet.mvc.method.annotation)
invokeHandlerMethod:893, RequestMappingHandlerAdapter (org.springframework.web.servlet.mvc.method.annotation)
handleInternal:807, RequestMappingHandlerAdapter (org.springframework.web.servlet.mvc.method.annotation)
handle:87, AbstractHandlerMethodAdapter (org.springframework.web.servlet.mvc.method)
doDispatch:1061, DispatcherServlet (org.springframework.web.servlet)
doService:961, DispatcherServlet (org.springframework.web.servlet)
processRequest:1006, FrameworkServlet (org.springframework.web.servlet)
doPost:909, FrameworkServlet (org.springframework.web.servlet)
service:652, HttpServlet (javax.servlet.http)
service:883, FrameworkServlet (org.springframework.web.servlet)
service:733, HttpServlet (javax.servlet.http)
internalDoFilter:231, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilter:53, WsFilter (org.apache.tomcat.websocket.server)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:100, RequestContextFilter (org.springframework.web.filter)
doFilter:119, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:93, FormContentFilter (org.springframework.web.filter)
doFilter:119, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:201, CharacterEncodingFilter (org.springframework.web.filter)
doFilter:119, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:193, ApplicationFilterChain (org.apache.catalina.core)
doFilter:166, ApplicationFilterChain (org.apache.catalina.core)
invoke:202, StandardWrapperValve (org.apache.catalina.core)
invoke:97, StandardContextValve (org.apache.catalina.core)
invoke:542, AuthenticatorBase (org.apache.catalina.authenticator)
invoke:143, StandardHostValve (org.apache.catalina.core)
invoke:92, ErrorReportValve (org.apache.catalina.valves)
invoke:78, StandardEngineValve (org.apache.catalina.core)
service:343, CoyoteAdapter (org.apache.catalina.connector)
service:374, Http11Processor (org.apache.coyote.http11)
process:65, AbstractProcessorLight (org.apache.coyote)
process:868, AbstractProtocol$ConnectionHandler (org.apache.coyote)
doRun:1590, NioEndpoint$SocketProcessor (org.apache.tomcat.util.net)
run:49, SocketProcessorBase (org.apache.tomcat.util.net)
runWorker:1128, ThreadPoolExecutor (java.util.concurrent)
run:628, ThreadPoolExecutor$Worker (java.util.concurrent)
run:61, TaskThread$WrappingRunnable (org.apache.tomcat.util.threads)
run:829, Thread (java.lang)

**Comment by johnmiroki** [comment]
@ramfattah Thanks a lot!

**Comment by tracyboehrer** [comment]
@johnmiroki This is next on my list.  Ram and I will resolve it and include in the next patch release for Java.  I don't have a solid ETA on that release, but it's sooner rather than later.

**Comment by johnmiroki** [comment]
@tracyboehrer good to hear. Thank you very much!

**Comment by johnmiroki** [comment]
@tracyboehrer Hi Tracy, any ETA regarding this fix? Much appreciated!

**Comment by tracyboehrer** [comment]
The root of the problem is the 'choices.data' property.  It would appear this is a flattened JSON property.  I do believe that this should be an object under the 'choices' array.  It's a tricky issue and it will take me more research to understand this JSON notation.  What the existing FlatteningSerialzier is doing just doesn't handle it correctly.

In other words, I think a mitigating step is to change the JSON.

**Comment by johnmiroki** [comment]
@tracyboehrer agreed. It's rare to use a property as an object and an array at the same time. But the change should be from MS side. We as third party developers can't do much about it.
