### ISSUE TITLE
401 and trusted URL case sensitivity problems

### ISSUE THREAD

**Issue by clausman** [Microsoft/botbuilder-java#58]
Hello,

I have a bot using version 4.0.0-a1 which was running into problems integrating with Cortana. Whenever the bot attempted to send a reply back it would get a 401. I tracked it down to the authorization header not being set because the Cortana the request was being sent to `cortanabfchanneleastus.azurewebsites.net` which was not in the `trustHostNames` map in `MicrosoftAppCredentials`. Instead, the alternative casing `CortanaBFChannelEastUs.azurewebsites.net` of the same URL was in the map.

I verified the incoming activity had the mixed case version of the URL. I believe what might be happening is that somewhere in the building of the request URL the hostname is being lower cased. When checking with `MicrosoftAppCredentials` to see if this request is trusted and therefore allowed to add the Authentication header, there is no entry in the map because of the casing difference.

For now, I was able to work around the issue in our code by mutating the incoming activity with a lower case service URL before doing the `JwtTokenValidation` call.

I think the underlying issue can be fixed by changing `MicrosoftAppCredentials` to always use lowercase entries in `trustHostNames`, but wanted to check first before making/testing/posting any changes that this seems like an acceptable solution.

**Comment by daveta** [comment]
I believe this has been checked into the latest branch.  Can you verify?

**Comment by daveta** [comment]
Closing - feel free to reopen if you still have issues.

**Comment by clausman** [comment]
Thanks @daveta . Sorry for leaving this open and not getting around to verifying it. I will do as you say and reopen iff I have more issues after updating our version.

**Comment by kirankom** [comment]
I believe I am running into the same problem. I've tried with multiple version (4.0.0-SNAPSHOT and the 4.2-preview ones). The connector works with all channels except Cortana.
Below is my stack trace. Any help would greatly appreciated.


com.microsoft.bot.connector.models.ErrorResponseException: Status code 401, 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.bot.connector.implementation.ConversationsImpl.sendToConversationDelegate(ConversationsImpl.java:527)
	at com.microsoft.bot.connector.implementation.ConversationsImpl.access$200(ConversationsImpl.java:50)
	at com.microsoft.bot.connector.implementation.ConversationsImpl$12.call(ConversationsImpl.java:512)
	at com.microsoft.bot.connector.implementation.ConversationsImpl$12.call(ConversationsImpl.java:508)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.microsoft.bot.connector.implementation.ConversationsImpl.sendToConversation(ConversationsImpl.java:440)
	at com.alamere.bot.connector.MessageHandler.handle(MessageHandler.java:120)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.bot.connector.implementation.ConversationsImpl.sendToConversationDelegate(ConversationsImpl.java:527)
	at com.microsoft.bot.connector.implementation.ConversationsImpl.access$200(ConversationsImpl.java:50)
	at com.microsoft.bot.connector.implementation.ConversationsImpl$12.call(ConversationsImpl.java:512)
	at com.microsoft.bot.connector.implementation.ConversationsImpl$12.call(ConversationsImpl.java:508)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.microsoft.bot.connector.implementation.ConversationsImpl.sendToConversation(ConversationsImpl.java:440)
	at com.alamere.bot.connector.MessageHandler.handle(MessageHandler.java:120)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kirankom** [comment]
I missed clausman's comment about using a lowercase url BEFORE the JWT Validation. Once I do that it seems to work ok.
I used 4.2.0-preview-28 build from myGet. The issue still seems to be around.
